import {questions,startingPoints,SESSION_KEY,freshState,chooseFocus,readState,answerLabel,type Focus} from './quiz-v5';
const root=document.getElementById('quiz-app')!;
let state=freshState();
try {state=readState(sessionStorage.getItem(SESSION_KEY));} catch {}
const arrow='<svg width="21" height="21" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6" stroke="currentColor" stroke-width="1.7"/></svg>';
const esc=(text:string)=>text.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
function save(){try {sessionStorage.setItem(SESSION_KEY,JSON.stringify(state));} catch {}}
function commit(){save();render();window.scrollTo({top:0,behavior:'instant'});root.querySelector<HTMLElement>('h1,h2,legend')?.focus({preventScroll:true});}
function caption(){const count=questions.filter(q=>state.answers[q.id]).length;return `<div class="q5-progress"><span>${state.screen==='questions'?`Question ${state.index+1} of 10`:`${count} of 10 answered`}</span><span>${state.index<4?'Your experience':state.index<7?'What would help':'Getting started'}</span><progress aria-label="Questions answered" max="10" value="${count}">${count} of 10</progress></div>`;}
function render(){
  root.className=state.screen==='result'?'q5-result wrap':state.screen==='intro'?'q5-intro wrap':'q5-flow';
  if(state.screen==='intro') {
    root.innerHTML=`<div class="q5-intro-copy"><h1 tabindex="-1">Where does your<br><span>progress get stuck?</span></h1><p class="lead">Answer 10 questions about the setbacks you recognize and how you respond. Choose a focus and get an exercise to start working on the pattern today.</p><button class="button button-primary" id="start-quiz">Find my starting point ${arrow}</button><p class="button-note">Free. Your result is shown here. No email needed.</p><p class="q5-expect">Answer as you are today. You can change your answers along the way.</p></div><aside class="quiz-preview" aria-label="Preview of the first exercise"><div class="preview-heading"><h2>Your first exercise</h2><img src="/brand/symbol-ink.svg" width="42" height="42" alt=""></div><p class="preview-description">See how one missed plan can become a week of avoidance, and where a different response begins. A fictional example:</p><dl><div><dt>What happened?</dt><dd>I planned to check my spending on Sunday. A family visit ran late.</dd></div><div><dt>What did I tell myself?</dt><dd>“I’ve already fallen behind.”</dd></div><div><dt>What could I do next?</dt><dd>Open one bill after lunch on Monday.</dd></div></dl><a href="/vsl#first-practice">See the exercise</a></aside>`;
    document.getElementById('start-quiz')!.onclick=()=>{state.screen='questions';commit();};return;
  }
  if(state.screen==='bridge') {
    const second=state.index===6;
    root.innerHTML=`${caption()}<div class="q5-bridge"><img src="/brand/symbol-ink.svg" width="68" height="68" alt=""><h2 tabindex="-1">${second?'Choose how you’ll put this into practice.':'Look at the moment you pull back.'}</h2><p class="lead">${second?'The last few questions help you choose a format, a realistic pace and a change you want to notice in everyday life.':'Think about what happens between a setback and your next decision. The next questions help you look at the thought and response that follow.'}</p><div class="q5-bridge-note">${second?'You can try the written exercise before deciding whether the program is for you.':'If you’re unsure, choose the closest answer. You can change it later.'}</div><div class="question-actions"><button class="back-button" id="back">Back</button><button class="button button-primary" id="continue-bridge">Continue ${arrow}</button></div></div>`;
    document.getElementById('back')!.onclick=()=>{state.screen='questions';commit();};
    document.getElementById('continue-bridge')!.onclick=()=>{state.index++;state.screen='questions';commit();};return;
  }
  if(state.screen==='questions') {
    const q=questions[state.index];
    root.innerHTML=`${caption()}<form id="question-form"><fieldset><legend class="q5-title" tabindex="-1">${q.title}</legend><p class="question-hint" id="question-hint">${q.hint}</p><div class="q5-options" role="group" aria-describedby="question-hint">${q.options.map(o=>`<label class="q5-option"><input type="radio" name="answer" value="${o.id}" ${state.answers[q.id]===o.id?'checked':''}><span class="q5-radio" aria-hidden="true"></span><span>${esc(o.label)}</span></label>`).join('')}</div></fieldset><p id="answer-error" class="form-error" role="alert" hidden>Choose the answer that feels closest to continue.</p><div class="question-actions"><button class="back-button" type="button" id="back">Back</button><button class="button button-primary" type="submit" id="next-question">${state.index===9?'See my result':'Continue'} ${arrow}</button></div></form>`;
    root.querySelectorAll<HTMLInputElement>('input[name="answer"]').forEach(input=>input.addEventListener('change',()=>{state.answers[q.id]=input.value;save();document.getElementById('answer-error')!.hidden=true;}));
    document.getElementById('back')!.onclick=()=>{if(state.index===0)state.screen='intro';else state.index--;commit();};
    document.getElementById('question-form')!.onsubmit=event=>{event.preventDefault();if(!state.answers[q.id]){document.getElementById('answer-error')!.hidden=false;root.querySelector<HTMLInputElement>('input')?.focus();return;}if(state.index===9)state.screen='result';else if([3,6].includes(state.index))state.screen='bridge';else state.index++;commit();};return;
  }
  const focus=chooseFocus(state.answers);const point=startingPoints[focus];
  const chosen=state.answers.focus!=='open';
  root.innerHTML=`<div class="q5-result-copy"><h1 tabindex="-1">${point.title}</h1><p class="lead">${point.body}</p><p class="q5-result-context">${chosen?'This is the focus you chose.':'This suggestion is based on your answers.'} You can change it below.</p><div class="q5-first-step"><h2>Your first move</h2><p>${point.prompt}</p></div><a class="button button-primary" href="/vsl#first-practice">Work on this pattern ${arrow}</a><p class="button-note">Turn your answers into a specific next step. Try the free exercise and keep your notes.</p></div><aside class="q5-answer-sheet"><h2>Your answers</h2><dl>${['area','help','pace'].map(id=>`<div><dt>${id==='area'?'What matters':id==='help'?'What would help':'A pace that fits'}</dt><dd>${esc(answerLabel(id,state.answers))}</dd></div>`).join('')}</dl><details><summary>How this reflection works</summary><p>Your last answer chooses your focus. If you asked for a suggestion, we use the themes in answers 3, 4 and 5. When no theme stands out, we leave it open. This is a reflection, not a diagnosis.</p></details><button class="text-button" id="review-answers">Review my answers</button></aside><section class="q5-focus-switch"><h2>Want to explore something else?</h2><p>Choose another topic without taking the quiz again.</p><div class="q5-focus-buttons">${(['money','capacity','expectations'] as Focus[]).map(key=>`<button type="button" data-refocus="${key}" aria-pressed="${focus===key}">${startingPoints[key].name}</button>`).join('')}</div></section>`;
  document.getElementById('review-answers')!.onclick=()=>{state.index=0;state.screen='questions';commit();};
  root.querySelectorAll<HTMLButtonElement>('[data-refocus]').forEach(b=>b.onclick=()=>{state.answers.focus=b.dataset.refocus!;commit();});
}
document.getElementById('clear-v5')!.onclick=()=>{state=freshState();try{sessionStorage.removeItem(SESSION_KEY);}catch{}render();window.scrollTo({top:0,behavior:'instant'});root.querySelector<HTMLElement>('h1')?.focus();};
render();
