const fs = require('node:fs');
const path = require('node:path');
const deps = process.env.CODEX_NODE_MODULES || 'C:/Users/User/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const sharp = require(path.join(deps, 'sharp'));
const { GlobalFonts, convertSVGTextToPath } = require(path.join(deps, '@napi-rs/canvas'));
const root = path.resolve(__dirname, '../../..');
const v2 = path.join(root, '03-MARCA/PROTOCOL44-V2');
const pack = path.join(root, '03-MARCA/PROTOCOL44-CHECKOUT-KIT');
const web = path.resolve(__dirname, '../public/brand');
const fonts = path.resolve(__dirname, '../public/fonts');
for (const dir of [pack, web, fonts, path.join(pack, 'logos'), path.join(pack, 'icons'), path.join(pack, 'covers'), path.join(pack, 'source')]) fs.mkdirSync(dir, { recursive: true });
GlobalFonts.registerFromPath(path.join(v2, 'fonts/manrope-800.ttf'), 'P44Mark');
GlobalFonts.registerFromPath(path.join(v2, 'fonts/manrope-600.ttf'), 'P44Head');
GlobalFonts.registerFromPath(path.join(v2, 'fonts/sourcesans3-400.ttf'), 'P44Body');
const colors = { ink: '#202724', paper: '#F4F0E7', copper: '#A9422B', black: '#000000', white: '#FFFFFF' };
const mark = 'M25 5H39L18 65H4ZM89 5H103L82 65H68ZM47 5H61V107H47ZM111 5H125V107H111ZM4 65H143V79H4Z';
const micro = 'M8 6H11L7 18H4ZM20 6H23L19 18H16ZM13 6H16V26H13ZM25 6H28V26H25ZM4 18H28V21H4Z';
const svg = (w,h,body) => `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><title>Protocol 44</title>${body}</svg>`;
const text = (x,y,s,f,c,t) => `<text x="${x}" y="${y}" font-family="${f}" font-size="${s}" fill="${c}" letter-spacing="${f === 'P44Mark' ? '-1' : '-0.7'}">${t}</text>`;
const manifest = [];
async function save(name, raw, width, webName) {
  fs.writeFileSync(path.join(pack, 'source', name.replaceAll('/', '-') + '.svg'), raw);
  const vector = Buffer.from(convertSVGTextToPath(raw));
  fs.writeFileSync(path.join(pack, name + '.svg'), vector);
  await sharp(vector).resize({ width }).withMetadata({ exif: { IFD0: { ImageDescription: 'Protocol 44. Original vector artwork refined from Protocol44 V2. Generated by scripts/brand-assets.cjs, 2026-09-07.' } } }).png().toFile(path.join(pack, name + '.png'));
  if (webName) fs.writeFileSync(path.join(web, webName), vector);
  manifest.push({ name, width, source: 'Native vector; V2 monogram and self-hosted Manrope; no generative raster' });
}
(async () => {
  for (const [name, c] of Object.entries(colors)) {
    const lock = svg(478,80, `<path fill="${c}" transform="translate(2 5) scale(.63)" d="${mark}"/>${text(114,54,44,'P44Mark',c,'PROTOCOL 44')}`);
    await save('logos/logo-' + name, lock, 1434, 'logo-' + name + '.svg');
    await save('logos/symbol-' + name, svg(160,160,`<path fill="${c}" transform="translate(8 24)" d="${mark}"/>`), 960, 'symbol-' + name + '.svg');
    await save('logos/wordmark-' + name, svg(452,76,text(6,56,54,'P44Mark',c,'PROTOCOL 44')), 1356);
  }
  const favicon = svg(32,32,`<rect width="32" height="32" rx="6" fill="${colors.ink}"/><path fill="${colors.paper}" d="${micro}"/>`);
  fs.writeFileSync(path.join(pack,'icons/favicon.svg'),favicon);
  fs.writeFileSync(path.join(web,'favicon.svg'),favicon);
  for (const s of [16,32,48,64,180,192,512]) {
    // Micro master stays open at tab size. Larger app icons use the original master.
    const raw = s <= 64 ? favicon : svg(512,512,`<rect width="512" height="512" fill="${colors.ink}"/><path fill="${colors.paper}" transform="translate(91 122) scale(2.3)" d="${mark}"/>`);
    await sharp(Buffer.from(raw)).resize(s,s).png().toFile(path.join(pack,`icons/icon-${s}.png`));
    fs.copyFileSync(path.join(pack,`icons/icon-${s}.png`),path.join(web,`icon-${s}.png`));
  }
  const frames = await Promise.all([16,32,48].map(s=>fs.promises.readFile(path.join(pack,`icons/icon-${s}.png`))));
  const head = Buffer.alloc(6+16*frames.length); head.writeUInt16LE(1,2);head.writeUInt16LE(frames.length,4);let off=head.length;
  frames.forEach((b,i)=>{ const p=6+i*16;head[p]=[16,32,48][i];head[p+1]=head[p];head.writeUInt16LE(1,p+4);head.writeUInt16LE(32,p+6);head.writeUInt32LE(b.length,p+8);head.writeUInt32LE(off,p+12);off+=b.length; });
  const ico=Buffer.concat([head,...frames]);fs.writeFileSync(path.join(pack,'icons/favicon.ico'),ico);fs.writeFileSync(path.join(web,'favicon.ico'),ico);
  await save('covers/product-square', svg(1200,1200,`<rect width="1200" height="1200" fill="${colors.copper}"/>${text(80,130,44,'P44Mark',colors.paper,'PROTOCOL 44')}<path fill="${colors.paper}" transform="translate(228 262) scale(5.2)" d="${mark}"/>${text(80,1032,64,'P44Head',colors.paper,'For keeps.')}${text(80,1112,32,'P44Body',colors.paper,'Lessons. Audio practices. Reflection.')}`),1200);
  await save('covers/vsl-poster', svg(1600,900,`<rect width="1600" height="900" fill="${colors.copper}"/>${text(88,115,38,'P44Mark',colors.paper,'PROTOCOL 44')}${text(86,350,100,'P44Head',colors.paper,'Make room')}${text(86,469,100,'P44Head',colors.paper,'for what')}${text(86,588,100,'P44Head',colors.paper,'stays.')}<path fill="${colors.paper}" transform="translate(1000 257) scale(3.3)" d="${mark}"/><path d="M88 726H1512" stroke="${colors.paper}" stroke-width="1"/>${text(88,805,30,'P44Body',colors.paper,'The Reading / The Move / The Hold')}${text(1350,805,30,'P44Body',colors.paper,'For keeps.')}`),1600,'vsl-poster.svg');
  await save('covers/social-share', svg(1200,630,`<rect width="1200" height="630" fill="${colors.paper}"/>${text(70,100,36,'P44Mark',colors.ink,'PROTOCOL 44')}${text(68,285,74,'P44Head',colors.ink,'Make room for')}${text(68,374,74,'P44Head',colors.ink,'what stays.')}<path fill="${colors.copper}" transform="translate(850 230) scale(1.9)" d="${mark}"/>${text(70,550,28,'P44Body',colors.ink,'A guided program for reflection and practice.')}`),1200);
  fs.copyFileSync(path.join(pack,'covers/social-share.png'),path.join(web,'social-share.png'));
  fs.copyFileSync(path.join(pack,'covers/vsl-poster.png'),path.join(web,'vsl-poster.png'));
  for(const f of ['manrope.ttf','sourcesans3.ttf','manrope-OFL.txt','sourcesans3-OFL.txt']) fs.copyFileSync(path.join(v2,'fonts',f),path.join(fonts,f));
  fs.writeFileSync(path.join(web,'site.webmanifest'),JSON.stringify({name:'Protocol 44',short_name:'Protocol 44',icons:[192,512].map(s=>({src:`/brand/icon-${s}.png`,sizes:`${s}x${s}`,type:'image/png'})),theme_color:colors.paper,background_color:colors.paper,display:'browser'},null,2));
  fs.copyFileSync(path.join(web,'site.webmanifest'),path.join(pack,'icons/site.webmanifest'));
  fs.writeFileSync(path.join(pack,'PROVENANCE.json'),JSON.stringify({date:'2026-09-07',version:'2.1',files:manifest},null,2));
  fs.copyFileSync(__filename,path.join(pack,'source/brand-assets.cjs'));
  console.log(JSON.stringify({pack,web,compositions:manifest.length}));
})().catch(e=>{console.error(e);process.exit(1)});
