const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.P44_PLAYWRIGHT_MODULE||'playwright');
const out=path.resolve(process.env.P44_REVIEW_DIR||'.impeccable/review/v5');fs.mkdirSync(out,{recursive:true});
fs.writeFileSync(path.join(out,'quiz-data.cjs'),require('esbuild').transformSync(fs.readFileSync('src/lib/quiz-v5.ts','utf8'),{loader:'ts',format:'cjs'}).code);
const Q=require(path.join(out,'quiz-data.cjs')),checks=[],images=[],errors=[],BASE=process.env.P44_BASE_URL||'http://127.0.0.1:4322';
function check(name,fn){fn();checks.push(name);}
check('Final choice leads; ties and neutral answers stay open',()=>{assert.equal(Q.chooseFocus({focus:'capacity',pressure:'money'}),'capacity');assert.equal(Q.chooseFocus({focus:'open',pressure:'money',response:'capacity',thought:'none'}),'open');assert.equal(Q.chooseFocus({focus:'open',pressure:'money',response:'money'}),'money');assert.equal(Q.chooseFocus({focus:'open'}),'open');});
check('Invalid storage and incomplete results recover',()=>{assert.equal(Q.readState('invalid').screen,'intro');assert.equal(Q.readState(JSON.stringify({version:5,screen:'result',index:9,answers:{area:'bad'}})).index,0);assert.equal(Q.readState(JSON.stringify({version:5,screen:'bridge',index:9,answers:{}})).screen,'questions');});
check('Ten questions and unique options',()=>{assert.equal(Q.questions.length,10);assert.equal(new Set(Q.questions.map(q=>q.id)).size,10);for(const q of Q.questions)assert.equal(new Set(q.options.map(o=>o.id)).size,q.options.length);});
async function capture(p,name){await p.mouse.move(0,0);await p.evaluate(()=>scrollTo(0,0));await p.evaluate(()=>document.fonts.ready);await p.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>i.decode().catch(()=>{}))));await p.screenshot({path:path.join(out,name+'.png'),fullPage:true,animations:'disabled'});const v=await p.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,images:[...document.images].every(i=>i.complete&&i.naturalWidth>0),font:document.fonts.check('600 22px Manrope')}));assert(v.scrollWidth<=v.viewport,name+' overflow');assert(v.images,name+' image');assert(v.font,name+' font');images.push({name,...v});}
function watch(p){p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400&&r.url().startsWith(BASE))errors.push(r.status()+' '+r.url());});}
const values=['work','fades','capacity','capacity','capacity','return','flexible','write','resume','capacity'];
const answers=Object.fromEntries(Q.questions.map((q,i)=>[q.id,values[i]]));
async function seed(p,a){await p.evaluate(({k,a})=>sessionStorage.setItem(k,JSON.stringify({version:5,screen:'result',index:9,answers:a})),{k:Q.SESSION_KEY,a});}
(async()=>{const b=await chromium.launch({headless:true,...(process.env.P44_CHROME_PATH?{executablePath:process.env.P44_CHROME_PATH}:{})});try{
 const p=await b.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});watch(p);await p.goto(BASE+'/quiz');await p.locator('#start-quiz').click();await p.locator('#next-question').click();assert(await p.locator('#answer-error').isVisible());
 for(let i=0;i<10;i++){await p.locator(`input[value="${values[i]}"]`).check();if(i===1){await p.locator('#back').click();assert(await p.locator('input[value="work"]').isChecked());await p.locator('#next-question').click();assert(await p.locator('input[value="fades"]').isChecked());}await p.locator('#next-question').click();if([3,6].includes(i))await p.locator('#continue-bridge').click();}
 await p.locator('.q5-result h1').waitFor();assert((await p.locator('h1').innerText()).includes('room'));await p.reload();assert(await p.locator('.q5-result').isVisible());checks.push('Full flow: ten questions, bridges, validation, back and restore');
 await p.locator('[data-refocus="money"]').click();assert((await p.locator('h1').innerText()).includes('money'));await p.locator('.q5-result-copy a.button').click();await p.locator('#practice-focus').waitFor();assert((await p.locator('#practice-focus').innerText()).includes('money'));checks.push('Change focus and preserve context into practice');
 await p.locator('#first-practice-form button').click();assert((await p.locator('#practice-status').innerText()).includes('at least one'));await p.locator('#practice-event').fill('I missed a planned review.');await p.locator('#practice-next').fill('Open one bill after lunch.');const waiting=p.waitForEvent('download');await p.locator('#first-practice-form button').click();const d=await waiting;assert.equal(d.suggestedFilename(),'Protocol-44-my-first-reflection.txt');await d.saveAs(path.join(out,'sample-reflection.txt'));assert(fs.readFileSync(path.join(out,'sample-reflection.txt'),'utf8').includes('Open one bill after lunch.'));await p.reload();assert.equal(await p.locator('#practice-event').inputValue(),'');checks.push('Private worksheet, validation and real download');
 await p.goto(BASE+'/');for(const n of [1,2,0]){await p.locator(`[data-example-step="${n}"]`).press('Enter');assert.equal(await p.locator(`[data-example-step="${n}"]`).getAttribute('aria-pressed'),'true');assert(await p.locator(`[data-example-panel="${n}"]`).isVisible());}await p.locator('.faqs summary').first().click();assert(await p.locator('.faqs details').first().getAttribute('open')!==null);checks.push('Keyboard example switching and FAQ');
 assert.equal(await p.locator('html').getAttribute('lang'),'en');assert.equal(await p.locator('meta[name="robots"]').getAttribute('content'),'noindex,nofollow');assert.equal(await p.locator('video').count(),0);
 for(const width of [1440,390]){await p.setViewportSize({width,height:width>760?1000:844});await p.goto(BASE+'/');await capture(p,`home-${width}`);await p.evaluate(k=>sessionStorage.removeItem(k),Q.SESSION_KEY);await p.goto(BASE+'/quiz');await capture(p,`quiz-intro-${width}`);await p.locator('#start-quiz').click();await capture(p,`quiz-question-${width}`);await seed(p,answers);await p.reload();await capture(p,`quiz-result-${width}`);await p.goto(BASE+'/vsl');await capture(p,`vsl-${width}`);}
 for(const width of [320,393,1280]){await p.setViewportSize({width,height:900});for(const route of ['/','/quiz','/vsl']){await p.goto(BASE+route);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),route+' @'+width);}}checks.push('Responsive widths: 320, 390, 393, 1280, 1440');
 for(const focus of ['money','capacity','expectations','open']){await seed(p,{...answers,focus,...(focus==='open'?{pressure:'unsure',response:'other',thought:'none'}:{})});await p.goto(BASE+'/quiz');assert.equal(await p.locator('h1').innerText(),Q.startingPoints[focus].title);}checks.push('Three focuses and an open result');
 for(const a of [{...answers,focus:'money'},{...answers,focus:'open',pressure:'money',response:'money',thought:'money'},{...answers,focus:'open',pressure:'unsure',response:'other',thought:'none'}]){await seed(p,a);await p.goto(BASE+'/vsl');assert.equal(await p.locator('#vsl-context').innerText(),`Your focus is “${Q.startingPoints[Q.chooseFocus(a)].name}.” Let’s work through an example from your week.`);}checks.push('Practice context stays accurate for chosen, suggested and open focuses');
 await p.goto(BASE+'/quiz');await p.locator('.site-footer summary').click();await p.locator('#clear-v5').click();assert(await p.locator('#start-quiz').isVisible());assert.equal(await p.evaluate(k=>sessionStorage.getItem(k),Q.SESSION_KEY),null);checks.push('Clear answers removes the V5 session');
 await p.goto(BASE+'/quiz-v4');await p.locator('#btn-start').waitFor();await p.locator('#btn-start').click();assert((await p.locator('#app').innerText()).includes('O que mais te motiva'));checks.push('V4 remains accessible in Portuguese');
 const n=await b.newPage({viewport:{width:1440,height:1000},reducedMotion:'no-preference'});watch(n);await n.goto(BASE+'/');await n.locator('#example-story').scrollIntoViewIfNeeded();await n.locator('[data-example-step="2"]').click();assert(await n.locator('[data-example-panel="2"]').isVisible());await n.emulateMedia({reducedMotion:'reduce'});await n.locator('[data-example-step="1"]').click();assert(await n.locator('[data-example-panel="1"]').isVisible());checks.push('Motion mode and live reduced-motion change');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'VERIFICACAO-V5.json'),JSON.stringify({date:new Date().toISOString(),checks,images,errors},null,2));console.log(JSON.stringify({checks:checks.length,screenshots:images.length,errors},null,2));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
